"""change column name to from_admin

Revision ID: 469d887aa116
Revises: 1cff3aa1d7e7
Create Date: 2019-05-03 00:55:38.886335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469d887aa116'
down_revision = '1cff3aa1d7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('from_admin', sa.Boolean(), nullable=True))
    op.drop_column('comment', 'form_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('form_admin', sa.BOOLEAN(), nullable=True))
    op.drop_column('comment', 'from_admin')
    # ### end Alembic commands ###
